fruits_and_veggies = [
    'artichoke',
    'asparagus',
    'broccoli',
    'cabbage',
    'cauliflower',
    'celery',
    'lettuce',
    'collard greens',
    'spinach',
    'black beans',
    'pinto beans',
    'soy beans',
    'peas',
    'peanuts',
    'kidney beans',
    'bean sprouts',
    'okra',
    'onion',
    'garlic',
    'leek',
    'chives',
    'spring onion',
    'bell pepper',
    'chili pepper',
    'jalapeno',
    'paprika',
    'habanero',
    'radicchio',
    'carrot',
    'ginger',
    'parsnip',
    'radish',
    'horseradish',
    'potato',
    'sweet potato',
    'turnip',
    'butternut squash',
    'cucumber',
    'tomato',
    'apple',
    'apricot',
    'avocado',
    'banana',
    'blackberry',
    'blackcurrant',
    'blueberry',
    'cactus pear',
    'cherry',
    'coconut',
    'cranberry',
    'dragonfruit',
    'date',
    'currant',
    'durian',
    'elderberry',
    'fig',
    'goji berry',
    'grape',
    'raisin',
    'grapefruit',
    'guava',
    'jackfruit',
    'lemon',
    'lime',
    'pumpkin',
    'zucchini',
    'eggplant',
    'corn',
    'lychee',
    'mango',
    'melon',
    'watermelon',
    'orange',
    'clementine',
    'mandarine',
    'tangerine',
    'papaya',
    'passionfruit',
    'peach',
    'pearplum',
    'prune',
    'pineapple',
    'pomelo',
    'raspberry',
    'rambutan',
    'strawberry',
    'olive'
]